id: P79CC9223
initial_creation_type: ocr
source_metadata:
  volumes:
    bd5b2b78d076439f98d7c1a1ff165e6a:
      base_file: v012.txt
      image_group_id: I1PD95857
      title: རྡོ་རྗེ་རྣལ་འབྱོར་མ་ལ་བསྟོད་པ།
      total_pages: 1544
      volume_number: 12
